--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MyDeacy/ServerDocument-PMMP
build-by-default: true
branches:
- master
projects:
  ServerDocument-PMMP:
    path: ""
    icon: "images/icon.png"
...
