name: ServerDocument
api: [3.9]
version: 1.0.0
main: net\mydeacy\serverdocument\ServerDocument
author: MyDeacy
description: View text files from server
commands:
 sd:
   description: open document directory.
   usage: /sd